### ISSUE TITLE
Add some Topics / Tags to this repo

### ISSUE THREAD

**Issue by manuel3108** [svelte-add/svelte-adders#15]
I have just noticed, that this repo does not have topics / tags.
![image](https://user-images.githubusercontent.com/30698007/111362041-a3695780-868e-11eb-869f-367eeaeb544c.png)

I think we could add a few of them.

To name a few:

svelte
svelte-kit
sveltekit
svelte-add
svelte-adder
svelte-adders

**Comment by babichjacob** [comment]
`svelte-adder` is going to be the preferred tag for adders. Thanks!

**Comment by babichjacob** [comment]
Nevermind, switching to `svelte-add` from `svelte-adder`.
