### ISSUE TITLE
Cannot login to Github to pull

### ISSUE THREAD

**Issue by sisou** [svelte-add/svelte-adders#18]
I'm trying to add the tailwind adder to a fresh SvelteKit project. I installed `svelte-add` globally with yarn.

Running `svelte-add tailwind` requires me to log into Github with username and password, which I have not set up on my computer (why no SSH?). I am very certain I enter the password correctly, but it still fails to login and to clone. I have 2FA enabled on my Github, can that be the reason it fails?

**Comment by sisou** [comment]
Turns out, the adder is called `tailwindcss`, not `tailwind`. That makes it work.

I think there should be an error message when the repo could not be found, like it did when I ran `npx apply svelte-add/tailwind` instead.

**Comment by babichjacob** [comment]
> Turns out, the adder is called `tailwindcss`, not `tailwind`. That makes it work.
> 
> I think there should be an error message when the repo could not be found, like it did when I ran `npx apply svelte-add/tailwind` instead.

This isn't within my/our control. We couldn't maintain an allowlist in this repository because it would harm adders that aren't in the `svelte-add` organization, which is unfair.
