### ISSUE TITLE
I had to change 'use-preset' to 'apply'

### ISSUE THREAD

**Issue by softgripper** [svelte-add/svelte-adders#4]
I think 'use-preset' has been changed to 'apply'

see https://usepreset.dev

```
/home/nedcol/.npm/_npx/7282/pnpm-global/4:
+ use-preset 0.2.12
npx: command not found: use-preset
```

Eg
```bash
pnpx apply svelte-add/tailwindcss
```
Seems to mostly work

**Comment by babichjacob** [comment]
Thank you for the heads up! I think every occurrence has been updated.

**Comment by websocket98765** [comment]
I had the opposite experience--`use-preset` worked and `apply` didn't. Using the latest SvelteKit (installed today) built on Vite and NPM `6.14.11`:

Apply didn't do anything:
```
❯ pnpx apply svelte-add/postcss    
usage: apply [-a magic] [-d] [-0123456789] command arguments ...
```

`use-preset` worked:
```
pnpx use-preset svelte-add/postcss
 WARN  use-preset: ts-bus@2.3.1 requires a peer of react@^16.8.6 but none was installed.
Packages: +133
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /Users/f/.pnpm-store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 133, reused 29, downloaded 104, added 133, done
node_modules/.pnpm/esbuild@0.8.57/node_modules/esbuild: Running postinstall script, done in 650ms

/Users/f/.npm/_npx/23910/pnpm-global/4:
+ use-preset 0.2.13
npx: command not found: use-preset
```

**Comment by babichjacob** [comment]
> I had the opposite experience--`use-preset` worked and `apply` didn't. Using the latest SvelteKit (installed today) built on Vite and NPM `6.14.11`:
> 
> Apply didn't do anything:
> 
> ```
> ❯ pnpx apply svelte-add/postcss    
> usage: apply [-a magic] [-d] [-0123456789] command arguments ...
> ```
> 
> `use-preset` worked:
> 
> ```
> pnpx use-preset svelte-add/postcss
>  WARN  use-preset: ts-bus@2.3.1 requires a peer of react@^16.8.6 but none was installed.
> Packages: +133
> +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
> Packages are hard linked from the content-addressable store to the virtual store.
>   Content-addressable store is at: /Users/f/.pnpm-store/v3
>   Virtual store is at:             node_modules/.pnpm
> Progress: resolved 133, reused 29, downloaded 104, added 133, done
> node_modules/.pnpm/esbuild@0.8.57/node_modules/esbuild: Running postinstall script, done in 650ms
> 
> /Users/f/.npm/_npx/23910/pnpm-global/4:
> + use-preset 0.2.13
> npx: command not found: use-preset
> ```

Please see https://github.com/preset/cli/issues/65. I know this is a problem that I'm going to try to experiment with solving soon.

**Comment by websocket98765** [comment]
Thanks. That is it--`man apply` shows a result for me too.
I should mention, I wasn't able to get tailwind working, like I could previously using this, but I'll try again later since SvelteKit is in flux.
